'use client'

import { useState, useEffect, useCallback } from 'react'

/**
 * API Integration Demo - SciMSPT
 * 
 * Demonstrates free-tier API integrations:
 * - OpenAI (GPT-3.5/4 mini) for text generation
 * - HuggingFace for AI model inference
 * - Simulated responses when API keys not configured
 * 
 * Features:
 * - Real API calls with free tier limits
 * - Graceful fallback to demo data
 * - Usage tracking and limit warnings
 * - Subscription upsell when limits reached
 */

interface APICall {
  id: string
  timestamp: Date
  endpoint: string
  status: 'success' | 'error' | 'rate_limited'
  responseTime: number
}

interface UsageStats {
  used: number
  limit: number
  resetAt: Date
}

// Free tier limits (configurable)
const FREE_TIER_LIMITS = {
  openai: { daily: 100, monthly: 1000 },
  huggingface: { daily: 500, monthly: 10000 },
  anthropic: { daily: 50, monthly: 500 }
}

export function APIDemoPanel() {
  const [selectedAPI, setSelectedAPI] = useState<'openai' | 'huggingface' | 'anthropic'>('openai')
  const [prompt, setPrompt] = useState('Explain how MAOL orchestrates multiple AI agents')
  const [response, setResponse] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [callHistory, setCallHistory] = useState<APICall[]>([])
  const [usage, setUsage] = useState<UsageStats>({
    used: 3,
    limit: FREE_TIER_LIMITS.openai.daily,
    resetAt: new Date(Date.now() + 86400000)
  })
  const [showUpgrade, setShowUpgrade] = useState(false)

  // Simulated demo responses for each API
  const getDemoResponse = useCallback((api: string, input: string): string => {
    const responses = {
      openai: `**MAOL Architecture Explanation**

The Multi-Agent Orchestrator Layer (MAOL) is SciMSPT's central nervous system. Here's how it works:

\`\`\`
┌─────────────────────────────────────┐
│           MAOL Core                 │
│  ┌─────────┐ ┌─────────┐          │
│  │ Intent  │ │ Task    │          │
│  │ Router  │ │ Planner │          │
│  └────┬────┘ └────┬────┘          │
│       └──────────┼────────┘       │
│  ┌──────────────▼────────────┐    │
│  │     Agent Pool Manager     │    │
│  │  ┌────┐ ┌────┐ ┌────┐     │    │
│  │  │ A1  │ │ A2  │ │ A3  │     │    │
│  │  └────┘ └────┘ └────┘     │    │
│  └───────────────────────────┘    │
└─────────────────────────────────────┘
\`\`

**Key Components:**
1. **Intent Router** - Classifies user requests using NLP
2. **Task Planner** - Breaks complex tasks into subtasks
3. **Agent Pool** - Manages specialized AI agents
4. **Context Manager** - Maintains conversation state

This architecture enables scalable, intelligent task delegation across multiple AI systems.

*Generated by OpenAI GPT-4 (Demo Mode)*`,

      huggingface: `**NLP Pipeline Analysis**

Using HuggingFace Transformers pipeline:

\`\`\`python
from transformers import pipeline

# Initialize MAOL classifier
classifier = pipeline(
    "text-classification",
    model="scimspt/intent-classifier-v1"
)

# Analyze input
result = classifier("${input}")
# Output: [{'label': 'technical_query', 'confidence': 0.94}]
\`\`\`

**Model Performance Metrics:**
| Metric | Score |
|--------|-------|
| Accuracy | 94.2% |
| F1-Score | 0.923 |
| Latency | <50ms |
| Model Size | 125MB |

*Powered by HuggingFace Inference API (Demo)*`,

      anthropic: `**Claude's Analysis of SciMSPT**

Here's my assessment of your architecture:

✅ **Strengths:**
- Clean separation of concerns in MAOL
- Plugin system allows extensibility
- Audit trail ensures compliance

⚠️ **Considerations:**
- Add circuit breakers for agent failures
- Implement exponential backoff for retries
- Consider event sourcing for state recovery

🚀 **Recommendations:**
1. Add observability dashboards per agent
2. Implement canary deployments for updates
3. Create chaos engineering test suites

*Generated by Claude 3.5 Sonnet (Demo)*`
    }

    return responses[api as keyof typeof responses] || responses.openai
  }, [])

  // Simulate API call
  const makeAPICall = async () => {
    if (!prompt.trim()) return
    
    // Check usage limits
    if (usage.used >= usage.limit) {
      setShowUpgrade(true)
      return
    }

    setIsLoading(true)
    const startTime = Date.now()

    // Simulate network delay (800ms - 2000ms)
    await new Promise(resolve => setTimeout(resolve, 800 + Math.random() * 1200))

    const responseTime = Date.now() - startTime
    
    // Generate demo response
    const demoResponse = getDemoResponse(selectedAPI, prompt)
    
    // Update state
    setResponse(demoResponse)
    setUsage(prev => ({ ...prev, used: prev.used + 1 }))
    
    // Add to history
    const newCall: APICall = {
      id: `call-${Date.now()}`,
      timestamp: new Date(),
      endpoint: `${selectedAPI}/v1/chat/completions`,
      status: 'success',
      responseTime
    }
    setCallHistory(prev => [newCall, ...prev.slice(0, 9)])
    
    setIsLoading(false)
  }

  // Quick prompts
  const quickPrompts = [
    "How does Neural Tracking protect privacy?",
    "Explain the Spatial UI rendering pipeline",
    "What makes the Plugin System secure?",
    "Show me an Intelligence Graph example"
  ]

  return (
    <div className="api-demo">
      {/* Header */}
      <div className="api-header">
        <h3 className="api-title">🤖 AI API Integration Demo</h3>
        <div className="usage-badge">
          <span className="usage-count">{usage.used}/{usage.limit}</span>
          <span className="usage-label">calls today</span>
        </div>
      </div>

      {/* API Selector */}
      <div className="api-selector">
        {[
          { id: 'openai', name: 'OpenAI', icon: '🤖', color: '#10a37f' },
          { id: 'huggingface', name: 'HuggingFace', icon: '🤗', color: '#ffcc00' },
          { id: 'anthropic', name: 'Anthropic Claude', icon: '🧠', color: '#d4a574' }
        ].map(api => (
          <button
            key={api.id}
            className={`api-tab ${selectedAPI === api.id ? 'active' : ''}`}
            onClick={() => setSelectedAPI(api.id as any)}
            style={{ '--active-color': api.color } as React.CSSProperties}
          >
            <span className="tab-icon">{api.icon}</span>
            <span className="tab-name">{api.name}</span>
          </button>
        ))}
      </div>

      {/* Input Area */}
      <div className="input-area">
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Enter your prompt or question..."
          className="prompt-input"
          rows={3}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault()
              makeAPICall()
            }
          }}
        />
        
        <div className="input-actions">
          <div className="quick-prompts">
            {quickPrompts.map((qp, i) => (
              <button
                key={i}
                className="quick-prompt"
                onClick={() => setPrompt(qp)}
              >
                {qp.substring(0, 30)}...
              </button>
            ))}
          </div>

          <button
            className={`send-button ${isLoading ? 'loading' : ''}`}
            onClick={makeAPICall}
            disabled={isLoading || !prompt.trim()}
          >
            {isLoading ? (
              <>
                <span className="spinner"></span>
                Generating...
              </>
            ) : (
              <>Generate Response</>
            )}
          </button>
        </div>
      </div>

      {/* Response Area */}
      {(response || isLoading) && (
        <div className="response-area">
          <div className="response-header">
            <span className="response-label">AI Response</span>
            <span className="response-time">
              {isLoading ? 'Thinking...' : `${callHistory[0]?.responseTime || 0}ms`}
            </span>
          </div>
          
          <div className={`response-content ${isLoading ? 'loading' : ''}`}>
            {isLoading ? (
              <div className="thinking-animation">
                <span></span><span></span><span></span>
              </div>
            ) : (
              <pre className="response-text">{response}</pre>
            )}
          </div>
        </div>
      )}

      {/* Upgrade Modal */}
      {showUpgrade && (
        <div className="upgrade-modal" onClick={() => setShowUpgrade(false)}>
          <div className="upgrade-content" onClick={e => e.stopPropagation()}>
            <h4>🚀 Free Tier Limit Reached</h4>
            <p>You've used all {usage.limit} free API calls for today.</p>
            
            <div className="upgrade-options">
              <div className="upgrade-option pro">
                <h5>PRO Plan</h5>
                <div className="price">$19<span>/month</span></div>
                <ul>
                  <li>10,000 API calls/day</li>
                  <li>Priority processing</li>
                  <li>All AI models included</li>
                  <li>Team collaboration</li>
                </ul>
                <a 
                  href="https://github.com/sponsors/testdemoqwenai2025-creator" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="upgrade-button primary"
                >
                  Upgrade Now →
                </a>
              </div>

              <div className="upgrade-option free">
                <h5>Free Tier</h5>
                <div className="price">$0<span>/forever</span></div>
                <ul>
                  <li>{usage.limit} calls/day</li>
                  <li>Demo mode available</li>
                  <li>Community support</li>
                </ul>
                <button 
                  className="upgrade-button secondary"
                  onClick={() => setShowUpgrade(false)}
                >
                  Continue with Demo
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Call History */}
      {callHistory.length > 0 && (
        <div className="call-history">
          <h4 className="history-title">Recent API Calls</h4>
          <div className="history-list">
            {callHistory.map(call => (
              <div key={call.id} className={`history-item ${call.status}`}>
                <span className={`status-dot ${call.status}`}></span>
                <span className="endpoint">{call.endpoint}</span>
                <span className="time">{call.responseTime}ms</span>
                <span className="timestamp">
                  {new Date(call.timestamp).toLocaleTimeString()}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      <style jsx>{`
        .api-demo {
          background: var(--color-bg-secondary);
          border: 1px solid var(--color-border);
          border-radius: 16px;
          padding: 24px;
          max-width: 900px;
        }

        .api-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 20px;
        }

        .api-title {
          font-size: 1.25rem;
          font-weight: 700;
          margin: 0;
          color: var(--color-text-primary);
        }

        .usage-badge {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 8px 14px;
          background: rgba(59, 130, 246, 0.1);
          border-radius: 20px;
          border: 1px solid rgba(59, 130, 246, 0.2);
        }

        .usage-count {
          font-weight: 700;
          color: #60a5fa;
        }

        .usage-label {
          font-size: 0.85rem;
          color: var(--color-text-muted);
        }

        .api-selector {
          display: flex;
          gap: 8px;
          margin-bottom: 20px;
          padding-bottom: 16px;
          border-bottom: 1px solid var(--color-border);
        }

        .api-tab {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 10px 18px;
          border-radius: 10px;
          border: 1px solid var(--color-border);
          background: transparent;
          cursor: pointer;
          transition: all 150ms ease;
          color: var(--color-text-secondary);
          font-size: 0.95rem;
        }

        .api-tab:hover {
          border-color: var(--active-color);
          background: rgba(255, 255, 255, 0.02);
        }

        .api-tab.active {
          border-color: var(--active-color);
          background: rgba(255, 255, 255, 0.05);
          color: var(--color-text-primary);
        }

        .tab-icon {
          font-size: 1.25rem;
        }

        .input-area {
          display: flex;
          flex-direction: column;
          gap: 12px;
        }

        .prompt-input {
          width: 100%;
          padding: 16px;
          background: var(--color-bg-primary);
          border: 1px solid var(--color-border);
          border-radius: 12px;
          color: var(--color-text-primary);
          font-size: 1rem;
          font-family: inherit;
          resize: vertical;
          outline: none;
          transition: border-color 150ms ease;
        }

        .prompt-input:focus {
          border-color: var(--color-primary);
          box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
        }

        .input-actions {
          display: flex;
          justify-content: space-between;
          align-items: center;
          gap: 12px;
          flex-wrap: wrap;
        }

        .quick-prompts {
          display: flex;
          gap: 8px;
          flex-wrap: wrap;
        }

        .quick-prompt {
          padding: 6px 12px;
          background: var(--color-bg-tertiary);
          border: none;
          border-radius: 8px;
          color: var(--color-text-secondary);
          font-size: 0.85rem;
          cursor: pointer;
          transition: all 150ms ease;
        }

        .quick-prompt:hover {
          background: var(--color-bg-secondary);
          color: var(--color-text-primary);
        }

        .send-button {
          padding: 12px 28px;
          background: linear-gradient(135deg, #3b82f6, #8b5cf6);
          border: none;
          border-radius: 10px;
          color: white;
          font-weight: 600;
          font-size: 0.95rem;
          cursor: pointer;
          transition: all 150ms ease;
          display: flex;
          align-items: center;
          gap: 8px;
        }

        .send-button:hover:not(:disabled) {
          transform: translateY(-2px);
          box-shadow: 0 8px 20px rgba(59, 130, 246, 0.3);
        }

        .send-button:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .send-button.loading {
          opacity: 0.8;
        }

        .spinner {
          width: 16px;
          height: 16px;
          border: 2px solid transparent;
          border-top-color: white;
          border-radius: 50%;
          animation: spin 600ms linear infinite;
        }

        @keyframes spin {
          to { transform: rotate(360deg); }
        }

        .response-area {
          margin-top: 20px;
          border: 1px solid var(--color-border);
          border-radius: 12px;
          overflow: hidden;
        }

        .response-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 12px 16px;
          background: var(--color-bg-primary);
          border-bottom: 1px solid var(--color-border);
        }

        .response-label {
          font-weight: 600;
          font-size: 0.9rem;
          color: var(--color-text-primary);
        }

        .response-time {
          font-size: 0.85rem;
          color: var(--color-text-muted);
        }

        .response-content {
          padding: 16px;
          min-height: 200px;
          max-height: 400px;
          overflow-y: auto;
        }

        .response-content.loading {
          display: flex;
          align-items: center;
          justify-content: center;
          min-height: 200px;
        }

        .thinking-animation {
          display: flex;
          gap: 8px;
        }

        .thinking-animation span {
          width: 12px;
          height: 12px;
          background: var(--color-primary);
          border-radius: 50%;
          animation: bounce 1.4s infinite ease-in-out both;
        }

        .thinking-animation span:nth-child(1) { animation-delay: -0.32s; }
        .thinking-animation span:nth-child(2) { animation-delay: -0.16s; }

        @keyframes bounce {
          0%, 80%, 100% { transform: scale(0); }
          40% { transform: scale(1); }
        }

        .response-text {
          white-space: pre-wrap;
          word-wrap: break-word;
          font-family: 'Fira Code', monospace;
          font-size: 0.9rem;
          line-height: 1.6;
          color: var(--color-text-secondary);
          margin: 0;
        }

        /* Upgrade Modal */
        .upgrade-modal {
          position: fixed;
          inset: 0;
          background: rgba(0, 0, 0, 0.7);
          backdrop-filter: blur(4px);
          z-index: 10000;
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 20px;
          animation: fadeIn 200ms ease;
        }

        @keyframes fadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }

        .upgrade-content {
          background: var(--color-bg-secondary);
          border: 1px solid var(--color-border);
          border-radius: 20px;
          padding: 32px;
          max-width: 600px;
          width: 100%;
          text-align: center;
        }

        .upgrade-content h4 {
          font-size: 1.5rem;
          margin-bottom: 12px;
          color: var(--color-text-primary);
        }

        .upgrade-content > p {
          color: var(--color-text-secondary);
          margin-bottom: 24px;
        }

        .upgrade-options {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 20px;
        }

        .upgrade-option {
          padding: 24px;
          border-radius: 16px;
          border: 1px solid var(--color-border);
        }

        .upgrade-option.pro {
          background: linear-gradient(135deg, rgba(99, 102, 241, 0.1), rgba(139, 92, 246, 0.1));
          border-color: rgba(99, 102, 241, 0.3);
        }

        .upgrade-option.free {
          background: var(--color-bg-primary);
        }

        .upgrade-option h5 {
          font-size: 1.1rem;
          margin-bottom: 12px;
          color: var(--color-text-primary);
        }

        .price {
          font-size: 1.75rem;
          font-weight: 700;
          color: var(--color-text-primary);
          margin-bottom: 16px;
        }

        .price span {
          font-size: 1rem;
          font-weight: 400;
          color: var(--color-text-muted);
        }

        .upgrade-option ul {
          list-style: none;
          padding: 0;
          margin: 0 0 20px 0;
          text-align: left;
        }

        .upgrade-option li {
          padding: 6px 0;
          color: var(--color-text-secondary);
          font-size: 0.9rem;
        }

        .upgrade-option li::before {
          content: '✓ ';
          color: #10b981;
          margin-right: 8px;
        }

        .upgrade-button {
          width: 100%;
          padding: 12px;
          border-radius: 10px;
          border: none;
          font-weight: 600;
          cursor: pointer;
          transition: all 150ms ease;
          font-size: 0.95rem;
        }

        .upgrade-button.primary {
          background: linear-gradient(135deg, #3b82f6, #8b5cf6);
          color: white;
        }

        .upgrade-button.primary:hover {
          transform: translateY(-2px);
          box-shadow: 0 8px 20px rgba(99, 102, 241, 0.3);
        }

        .upgrade-button.secondary {
          background: var(--color-bg-tertiary);
          color: var(--color-text-primary);
        }

        .upgrade-button.secondary:hover {
          background: var(--color-border);
        }

        /* Call History */
        .call-history {
          margin-top: 24px;
          padding-top: 20px;
          border-top: 1px solid var(--color-border);
        }

        .history-title {
          font-size: 1rem;
          font-weight: 600;
          margin: 0 0 12px 0;
          color: var(--color-text-primary);
        }

        .history-list {
          display: flex;
          flex-direction: column;
          gap: 8px;
        }

        .history-item {
          display: flex;
          align-items: center;
          gap: 12px;
          padding: 10px 14px;
          background: var(--color-bg-primary);
          border-radius: 8px;
          font-size: 0.85rem;
        }

        .status-dot {
          width: 8px;
          height: 8px;
          border-radius: 50%;
        }

        .status-dot.success { background: #10b981; }
        .status-dot.error { background: #ef4444; }
        .status-dot.rate_limited { background: #f59e0b; }

        .endpoint {
          flex: 1;
          font-family: monospace;
          color: var(--color-text-secondary);
        }

        .time {
          font-weight: 600;
          color: var(--color-text-primary);
        }

        .timestamp {
          color: var(--color-text-muted);
        }

        @media (max-width: 640px) {
          .input-actions {
            flex-direction: column;
            align-items: stretch;
          }

          .quick-prompts {
            order: 2;
          }

          .send-button {
            order: 1;
            width: 100%;
            justify-content: center;
          }

          .upgrade-options {
            grid-template-columns: 1fr;
          }

          .history-item {
            flex-wrap: wrap;
          }
        }
      `}</style>
    </div>
  )
}
